from pathlib import Path
p=Path('CMakeLists.txt')
s=p.read_text().replace('ProductionAuthoring.cppm AdvancedProductionAuthoring.cppm NativeGameplayAuthoring.cppm OfflineRenderAuthoring.cppm', 'ProductionAuthoring.cppm AdvancedProductionAuthoring.cppm NativeGameplayAuthoring.cppm OfflineRenderAuthoring.cppm ProductionSystemsAuthoring.cppm')
s=s.replace('tests/AdvancedProductionAuthoringTests.cpp)', 'tests/AdvancedProductionAuthoringTests.cpp tests/ProductionSystemsAuthoringTests.cpp)')
p.write_text(s)
p=Path('KairoEditor.cppm')
s=p.read_text().replace('export import Kairo.Editor.OfflineRenderAuthoring;\n', 'export import Kairo.Editor.OfflineRenderAuthoring;\nexport import Kairo.Editor.ProductionSystemsAuthoring;\n')
p.write_text(s)
Path('.github/workflows/wire-production-authoring.yml').unlink()
Path('.github/scripts/wire_production_authoring.py').unlink()
